/*
 * This file is generated by jOOQ.
 */
package org.imperial.mrc.hint.db.tables;


import java.util.Arrays;
import java.util.List;

import org.imperial.mrc.hint.db.Keys;
import org.imperial.mrc.hint.db.Public;
import org.imperial.mrc.hint.db.tables.records.AdrKeyRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdrKey extends TableImpl<AdrKeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.adr_key</code>
     */
    public static final AdrKey ADR_KEY = new AdrKey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdrKeyRecord> getRecordType() {
        return AdrKeyRecord.class;
    }

    /**
     * The column <code>public.adr_key.api_key</code>.
     */
    public final TableField<AdrKeyRecord, byte[]> API_KEY = createField(DSL.name("api_key"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.adr_key.user_id</code>.
     */
    public final TableField<AdrKeyRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CLOB, this, "");

    private AdrKey(Name alias, Table<AdrKeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private AdrKey(Name alias, Table<AdrKeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.adr_key</code> table reference
     */
    public AdrKey(String alias) {
        this(DSL.name(alias), ADR_KEY);
    }

    /**
     * Create an aliased <code>public.adr_key</code> table reference
     */
    public AdrKey(Name alias) {
        this(alias, ADR_KEY);
    }

    /**
     * Create a <code>public.adr_key</code> table reference
     */
    public AdrKey() {
        this(DSL.name("adr_key"), null);
    }

    public <O extends Record> AdrKey(Table<O> child, ForeignKey<O, AdrKeyRecord> key) {
        super(child, key, ADR_KEY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<AdrKeyRecord> getPrimaryKey() {
        return Keys.ADR_KEY_PKEY;
    }

    @Override
    public List<UniqueKey<AdrKeyRecord>> getKeys() {
        return Arrays.<UniqueKey<AdrKeyRecord>>asList(Keys.ADR_KEY_PKEY);
    }

    @Override
    public List<ForeignKey<AdrKeyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AdrKeyRecord, ?>>asList(Keys.ADR_KEY__ADR_KEY_USER_ID_FKEY);
    }

    private transient Users _users;

    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.ADR_KEY__ADR_KEY_USER_ID_FKEY);

        return _users;
    }

    @Override
    public AdrKey as(String alias) {
        return new AdrKey(DSL.name(alias), this);
    }

    @Override
    public AdrKey as(Name alias) {
        return new AdrKey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdrKey rename(String name) {
        return new AdrKey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdrKey rename(Name name) {
        return new AdrKey(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<byte[], String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
