/*
 * This file is generated by jOOQ.
*/
package org.imperial.mrc.hint.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.imperial.mrc.hint.db.Indexes;
import org.imperial.mrc.hint.db.Keys;
import org.imperial.mrc.hint.db.Public;
import org.imperial.mrc.hint.db.tables.records.SessionFilesRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionFiles extends TableImpl<SessionFilesRecord> {

    private static final long serialVersionUID = -1040305653;

    /**
     * The reference instance of <code>public.session_files</code>
     */
    public static final SessionFiles SESSION_FILES = new SessionFiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SessionFilesRecord> getRecordType() {
        return SessionFilesRecord.class;
    }

    /**
     * The column <code>public.session_files.session</code>.
     */
    public final TableField<SessionFilesRecord, String> SESSION = createField("session", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.session_files.pjnz</code>.
     */
    public final TableField<SessionFilesRecord, String> PJNZ = createField("pjnz", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.session_files.programme</code>.
     */
    public final TableField<SessionFilesRecord, String> PROGRAMME = createField("programme", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.session_files.survey</code>.
     */
    public final TableField<SessionFilesRecord, String> SURVEY = createField("survey", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.session_files.anc</code>.
     */
    public final TableField<SessionFilesRecord, String> ANC = createField("anc", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.session_files.shape</code>.
     */
    public final TableField<SessionFilesRecord, String> SHAPE = createField("shape", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.session_files</code> table reference
     */
    public SessionFiles() {
        this(DSL.name("session_files"), null);
    }

    /**
     * Create an aliased <code>public.session_files</code> table reference
     */
    public SessionFiles(String alias) {
        this(DSL.name(alias), SESSION_FILES);
    }

    /**
     * Create an aliased <code>public.session_files</code> table reference
     */
    public SessionFiles(Name alias) {
        this(alias, SESSION_FILES);
    }

    private SessionFiles(Name alias, Table<SessionFilesRecord> aliased) {
        this(alias, aliased, null);
    }

    private SessionFiles(Name alias, Table<SessionFilesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SESSION_FILES_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SessionFilesRecord> getPrimaryKey() {
        return Keys.SESSION_FILES_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SessionFilesRecord>> getKeys() {
        return Arrays.<UniqueKey<SessionFilesRecord>>asList(Keys.SESSION_FILES_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SessionFilesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SessionFilesRecord, ?>>asList(Keys.SESSION_FILES__SESSION_FILES_SESSION_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFiles as(String alias) {
        return new SessionFiles(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFiles as(Name alias) {
        return new SessionFiles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SessionFiles rename(String name) {
        return new SessionFiles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SessionFiles rename(Name name) {
        return new SessionFiles(name, null);
    }
}
