/*
 * This file is generated by jOOQ.
*/
package org.imperial.mrc.hint.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.imperial.mrc.hint.db.Indexes;
import org.imperial.mrc.hint.db.Keys;
import org.imperial.mrc.hint.db.Public;
import org.imperial.mrc.hint.db.tables.records.VersionFileRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VersionFile extends TableImpl<VersionFileRecord> {

    private static final long serialVersionUID = -1403326422;

    /**
     * The reference instance of <code>public.version_file</code>
     */
    public static final VersionFile VERSION_FILE = new VersionFile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VersionFileRecord> getRecordType() {
        return VersionFileRecord.class;
    }

    /**
     * The column <code>public.version_file.version</code>.
     */
    public final TableField<VersionFileRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.version_file.hash</code>.
     */
    public final TableField<VersionFileRecord, String> HASH = createField("hash", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.version_file.type</code>.
     */
    public final TableField<VersionFileRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.version_file.filename</code>.
     */
    public final TableField<VersionFileRecord, String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.version_file.from_adr</code>.
     */
    public final TableField<VersionFileRecord, Boolean> FROM_ADR = createField("from_adr", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.version_file</code> table reference
     */
    public VersionFile() {
        this(DSL.name("version_file"), null);
    }

    /**
     * Create an aliased <code>public.version_file</code> table reference
     */
    public VersionFile(String alias) {
        this(DSL.name(alias), VERSION_FILE);
    }

    /**
     * Create an aliased <code>public.version_file</code> table reference
     */
    public VersionFile(Name alias) {
        this(alias, VERSION_FILE);
    }

    private VersionFile(Name alias, Table<VersionFileRecord> aliased) {
        this(alias, aliased, null);
    }

    private VersionFile(Name alias, Table<VersionFileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VERSION_FILE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VersionFileRecord> getPrimaryKey() {
        return Keys.VERSION_FILE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VersionFileRecord>> getKeys() {
        return Arrays.<UniqueKey<VersionFileRecord>>asList(Keys.VERSION_FILE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VersionFileRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VersionFileRecord, ?>>asList(Keys.VERSION_FILE__VERSION_FILE_VERSION_FKEY, Keys.VERSION_FILE__VERSION_FILE_HASH_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionFile as(String alias) {
        return new VersionFile(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionFile as(Name alias) {
        return new VersionFile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VersionFile rename(String name) {
        return new VersionFile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VersionFile rename(Name name) {
        return new VersionFile(name, null);
    }
}
