/*
 * This file is generated by jOOQ.
*/
package org.imperial.mrc.hint.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.imperial.mrc.hint.db.Indexes;
import org.imperial.mrc.hint.db.Keys;
import org.imperial.mrc.hint.db.Public;
import org.imperial.mrc.hint.db.tables.records.VersionSnapshotRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VersionSnapshot extends TableImpl<VersionSnapshotRecord> {

    private static final long serialVersionUID = 2029406719;

    /**
     * The reference instance of <code>public.version_snapshot</code>
     */
    public static final VersionSnapshot VERSION_SNAPSHOT = new VersionSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VersionSnapshotRecord> getRecordType() {
        return VersionSnapshotRecord.class;
    }

    /**
     * The column <code>public.version_snapshot.id</code>.
     */
    public final TableField<VersionSnapshotRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.version_snapshot.version_id</code>.
     */
    public final TableField<VersionSnapshotRecord, Integer> VERSION_ID = createField("version_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.version_snapshot.state</code>.
     */
    public final TableField<VersionSnapshotRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.version_snapshot.note</code>.
     */
    public final TableField<VersionSnapshotRecord, String> NOTE = createField("note", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.version_snapshot.created</code>.
     */
    public final TableField<VersionSnapshotRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("timezone('utc'::text, now())", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.version_snapshot.updated</code>.
     */
    public final TableField<VersionSnapshotRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("timezone('utc'::text, now())", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.version_snapshot.deleted</code>.
     */
    public final TableField<VersionSnapshotRecord, Boolean> DELETED = createField("deleted", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.version_snapshot</code> table reference
     */
    public VersionSnapshot() {
        this(DSL.name("version_snapshot"), null);
    }

    /**
     * Create an aliased <code>public.version_snapshot</code> table reference
     */
    public VersionSnapshot(String alias) {
        this(DSL.name(alias), VERSION_SNAPSHOT);
    }

    /**
     * Create an aliased <code>public.version_snapshot</code> table reference
     */
    public VersionSnapshot(Name alias) {
        this(alias, VERSION_SNAPSHOT);
    }

    private VersionSnapshot(Name alias, Table<VersionSnapshotRecord> aliased) {
        this(alias, aliased, null);
    }

    private VersionSnapshot(Name alias, Table<VersionSnapshotRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VERSION_SNAPSHOT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VersionSnapshotRecord> getPrimaryKey() {
        return Keys.VERSION_SNAPSHOT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VersionSnapshotRecord>> getKeys() {
        return Arrays.<UniqueKey<VersionSnapshotRecord>>asList(Keys.VERSION_SNAPSHOT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VersionSnapshotRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VersionSnapshotRecord, ?>>asList(Keys.VERSION_SNAPSHOT__VERSION_SNAPSHOT_VERSION_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionSnapshot as(String alias) {
        return new VersionSnapshot(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionSnapshot as(Name alias) {
        return new VersionSnapshot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VersionSnapshot rename(String name) {
        return new VersionSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VersionSnapshot rename(Name name) {
        return new VersionSnapshot(name, null);
    }
}
