#!/usr/bin/env bash
set -ex

# Do not run if this is a pull request build - don't want to push to master yet
if [ $TRAVIS_PULL_REQUEST != "false" ]; then
   exit 0
fi

HERE=$(dirname $0)
. $HERE/common

$HERE/../../gradlew -p src :userCLI:distDocker -i -Pdocker_version=$GIT_SHA -Pdocker_name=$TAG_IMAGE;
