#!/usr/bin/env bash
set -ex

# Do not run if this is a pull request build - don't want to push to master yet
if [ $TRAVIS_PULL_REQUEST != "false" ]; then
   exit 0
fi

HERE=$(dirname $0)
. $HERE/common

docker tag $TAG_SHA $TAG_BRANCH
docker push $TAG_SHA
docker push $TAG_BRANCH