#!/usr/bin/env bash
set -ex
HERE=$(realpath "$(dirname $0)")

if [ "$BUILDKITE" = "true" ]; then
    GIT_ID=${BUILDKITE_COMMIT:0:7}
else
    # env var from github actions runner
    GIT_ID=$(git rev-parse --short=7 "$GITHUB_SHA")
fi

if [ "$BUILDKITE" = "true" ]; then
    GIT_BRANCH=$BUILDKITE_BRANCH
else
    # env var from github actions runner
    GIT_BRANCH=${GITHUB_REF#refs/heads/}
fi

# Deal with dependabot tags which look like
#
#   dependabot/npm_and_yarn/app/lodash-4.17.19
#
# But docker does not like
GIT_BRANCH=$(echo $GIT_BRANCH | sed 's;/;-;g')

BUILDKITE_DOCKER_AUTH_PATH=/var/lib/buildkite-agent/.docker/config.json

# Export env vars needed for running test dependencies
ORG=mrcide
echo "ORG=mrcide" >> $GITHUB_OUTPUT
echo "GIT_ID=$GIT_ID" >> $GITHUB_OUTPUT
echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_OUTPUT
echo "BUILD_ENV_TAG=$ORG/hint-shared-build-env:$GIT_ID" >> $GITHUB_OUTPUT
echo "APP_DOCKER_COMMIT_TAG=$ORG/hint:$GIT_ID" >> $GITHUB_OUTPUT
echo "APP_DOCKER_BRANCH_TAG=$ORG/hint:$GIT_BRANCH" >> $GITHUB_OUTPUT
echo "USER_CLI_COMMIT_TAG=$ORG/hint-user-cli:$GIT_ID" >> $GITHUB_OUTPUT
echo "USER_CLI_BRANCH_TAG=$ORG/hint-user-cli:$GIT_BRANCH" >> $GITHUB_OUTPUT
