/*
 * This file is generated by jOOQ.
*/
package org.imperial.mrc.hint.db;


import javax.annotation.Generated;

import org.imperial.mrc.hint.db.tables.OnetimeToken;
import org.imperial.mrc.hint.db.tables.SessionFiles;
import org.imperial.mrc.hint.db.tables.UserSession;
import org.imperial.mrc.hint.db.tables.Users;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ONETIME_TOKEN_PKEY = Indexes0.ONETIME_TOKEN_PKEY;
    public static final Index SESSION_FILES_PKEY = Indexes0.SESSION_FILES_PKEY;
    public static final Index USER_SESSION_PKEY = Indexes0.USER_SESSION_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ONETIME_TOKEN_PKEY = Internal.createIndex("onetime_token_pkey", OnetimeToken.ONETIME_TOKEN, new OrderField[] { OnetimeToken.ONETIME_TOKEN.TOKEN }, true);
        public static Index SESSION_FILES_PKEY = Internal.createIndex("session_files_pkey", SessionFiles.SESSION_FILES, new OrderField[] { SessionFiles.SESSION_FILES.SESSION }, true);
        public static Index USER_SESSION_PKEY = Internal.createIndex("user_session_pkey", UserSession.USER_SESSION, new OrderField[] { UserSession.USER_SESSION.SESSION }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
