/*
 * This file is generated by jOOQ.
 */
package org.imperial.mrc.hint.db;


import java.util.Arrays;
import java.util.List;

import org.imperial.mrc.hint.db.tables.AdrKey;
import org.imperial.mrc.hint.db.tables.File;
import org.imperial.mrc.hint.db.tables.OnetimeToken;
import org.imperial.mrc.hint.db.tables.Project;
import org.imperial.mrc.hint.db.tables.ProjectVersion;
import org.imperial.mrc.hint.db.tables.SessionFile;
import org.imperial.mrc.hint.db.tables.UserSession;
import org.imperial.mrc.hint.db.tables.Users;
import org.imperial.mrc.hint.db.tables.VersionFile;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.adr_key</code>.
     */
    public final AdrKey ADR_KEY = AdrKey.ADR_KEY;

    /**
     * The table <code>public.file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>public.onetime_token</code>.
     */
    public final OnetimeToken ONETIME_TOKEN = OnetimeToken.ONETIME_TOKEN;

    /**
     * The table <code>public.project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.project_version</code>.
     */
    public final ProjectVersion PROJECT_VERSION = ProjectVersion.PROJECT_VERSION;

    /**
     * The table <code>public.session_file</code>.
     */
    public final SessionFile SESSION_FILE = SessionFile.SESSION_FILE;

    /**
     * The table <code>public.user_session</code>.
     */
    public final UserSession USER_SESSION = UserSession.USER_SESSION;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>public.version_file</code>.
     */
    public final VersionFile VERSION_FILE = VersionFile.VERSION_FILE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.PROJECT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AdrKey.ADR_KEY,
            File.FILE,
            OnetimeToken.ONETIME_TOKEN,
            Project.PROJECT,
            ProjectVersion.PROJECT_VERSION,
            SessionFile.SESSION_FILE,
            UserSession.USER_SESSION,
            Users.USERS,
            VersionFile.VERSION_FILE);
    }
}
