/*
 * This file is generated by jOOQ.
 */
package org.imperial.mrc.hint.db;


import org.imperial.mrc.hint.db.tables.AdrKey;
import org.imperial.mrc.hint.db.tables.File;
import org.imperial.mrc.hint.db.tables.OnetimeToken;
import org.imperial.mrc.hint.db.tables.Project;
import org.imperial.mrc.hint.db.tables.ProjectVersion;
import org.imperial.mrc.hint.db.tables.SessionFile;
import org.imperial.mrc.hint.db.tables.UserSession;
import org.imperial.mrc.hint.db.tables.Users;
import org.imperial.mrc.hint.db.tables.VersionFile;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.adr_key</code>.
     */
    public static final AdrKey ADR_KEY = AdrKey.ADR_KEY;

    /**
     * The table <code>public.file</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>public.onetime_token</code>.
     */
    public static final OnetimeToken ONETIME_TOKEN = OnetimeToken.ONETIME_TOKEN;

    /**
     * The table <code>public.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.project_version</code>.
     */
    public static final ProjectVersion PROJECT_VERSION = ProjectVersion.PROJECT_VERSION;

    /**
     * The table <code>public.session_file</code>.
     */
    public static final SessionFile SESSION_FILE = SessionFile.SESSION_FILE;

    /**
     * The table <code>public.user_session</code>.
     */
    public static final UserSession USER_SESSION = UserSession.USER_SESSION;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.version_file</code>.
     */
    public static final VersionFile VERSION_FILE = VersionFile.VERSION_FILE;
}
