ARG GIT_ID="UNKNOWN"
FROM mrcide/hint-shared-build-env:$GIT_ID

ARG SPRING_PROFILE
ARG TAG

ENV NODE_ENV=production

RUN ./gradlew :app:bootDistTar

ENV SPRING_PROFILE=$SPRING_PROFILE
ENV TAG=$TAG

ARG OAUTH2_CLIENT_ID
ENV OAUTH2_CLIENT_ID=$OAUTH2_CLIENT_ID

ARG OAUTH2_CLIENT_SECRET
ENV OAUTH2_CLIENT_SECRET=$OAUTH2_CLIENT_SECRET

ARG OAUTH2_CLIENT_URL
ENV OAUTH2_CLIENT_URL=$OAUTH2_CLIENT_URL

CMD docker build --build-arg SPRING_PROFILES_ACTIVE=$SPRING_PROFILE -f /hint/Dockerfile --tag $TAG .
