/*
 * This file is generated by jOOQ.
 */
package org.imperial.mrc.hint.db.tables.records;


import org.imperial.mrc.hint.db.tables.AdrKey;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdrKeyRecord extends UpdatableRecordImpl<AdrKeyRecord> implements Record2<byte[], String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.adr_key.api_key</code>.
     */
    public void setApiKey(byte[] value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.adr_key.api_key</code>.
     */
    public byte[] getApiKey() {
        return (byte[]) get(0);
    }

    /**
     * Setter for <code>public.adr_key.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.adr_key.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<byte[]> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<byte[], String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<byte[], String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<byte[]> field1() {
        return AdrKey.ADR_KEY.API_KEY;
    }

    @Override
    public Field<String> field2() {
        return AdrKey.ADR_KEY.USER_ID;
    }

    @Override
    public byte[] component1() {
        return getApiKey();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public byte[] value1() {
        return getApiKey();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public AdrKeyRecord value1(byte[] value) {
        setApiKey(value);
        return this;
    }

    @Override
    public AdrKeyRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public AdrKeyRecord values(byte[] value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdrKeyRecord
     */
    public AdrKeyRecord() {
        super(AdrKey.ADR_KEY);
    }

    /**
     * Create a detached, initialised AdrKeyRecord
     */
    public AdrKeyRecord(byte[] apiKey, String userId) {
        super(AdrKey.ADR_KEY);

        setApiKey(apiKey);
        setUserId(userId);
    }
}
