/*
 * This file is generated by jOOQ.
 */
package org.imperial.mrc.hint.db.tables.records;


import org.imperial.mrc.hint.db.tables.OnetimeToken;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OnetimeTokenRecord extends UpdatableRecordImpl<OnetimeTokenRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.onetime_token.token</code>.
     */
    public void setToken(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.onetime_token.token</code>.
     */
    public String getToken() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OnetimeToken.ONETIME_TOKEN.TOKEN;
    }

    @Override
    public String component1() {
        return getToken();
    }

    @Override
    public String value1() {
        return getToken();
    }

    @Override
    public OnetimeTokenRecord value1(String value) {
        setToken(value);
        return this;
    }

    @Override
    public OnetimeTokenRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OnetimeTokenRecord
     */
    public OnetimeTokenRecord() {
        super(OnetimeToken.ONETIME_TOKEN);
    }

    /**
     * Create a detached, initialised OnetimeTokenRecord
     */
    public OnetimeTokenRecord(String token) {
        super(OnetimeToken.ONETIME_TOKEN);

        setToken(token);
    }
}
