/*
 * This file is generated by jOOQ.
 */
package org.imperial.mrc.hint.db.tables.records;


import org.imperial.mrc.hint.db.tables.Project;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> implements Record6<Integer, String, String, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.project.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.project.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.project.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.project.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.project.note</code>.
     */
    public void setNote(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.project.note</code>.
     */
    public String getNote() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.project.shared_by</code>.
     */
    public void setSharedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.project.shared_by</code>.
     */
    public String getSharedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.project.is_uploaded</code>.
     */
    public void setIsUploaded(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.project.is_uploaded</code>.
     */
    public Boolean getIsUploaded() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Project.PROJECT.ID;
    }

    @Override
    public Field<String> field2() {
        return Project.PROJECT.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Project.PROJECT.NAME;
    }

    @Override
    public Field<String> field4() {
        return Project.PROJECT.NOTE;
    }

    @Override
    public Field<String> field5() {
        return Project.PROJECT.SHARED_BY;
    }

    @Override
    public Field<Boolean> field6() {
        return Project.PROJECT.IS_UPLOADED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getNote();
    }

    @Override
    public String component5() {
        return getSharedBy();
    }

    @Override
    public Boolean component6() {
        return getIsUploaded();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getNote();
    }

    @Override
    public String value5() {
        return getSharedBy();
    }

    @Override
    public Boolean value6() {
        return getIsUploaded();
    }

    @Override
    public ProjectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProjectRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public ProjectRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProjectRecord value4(String value) {
        setNote(value);
        return this;
    }

    @Override
    public ProjectRecord value5(String value) {
        setSharedBy(value);
        return this;
    }

    @Override
    public ProjectRecord value6(Boolean value) {
        setIsUploaded(value);
        return this;
    }

    @Override
    public ProjectRecord values(Integer value1, String value2, String value3, String value4, String value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(Integer id, String userId, String name, String note, String sharedBy, Boolean isUploaded) {
        super(Project.PROJECT);

        setId(id);
        setUserId(userId);
        setName(name);
        setNote(note);
        setSharedBy(sharedBy);
        setIsUploaded(isUploaded);
    }
}
