/*
 * This file is generated by jOOQ.
*/
package org.imperial.mrc.hint.db.tables.records;


import javax.annotation.Generated;

import org.imperial.mrc.hint.db.tables.SessionFiles;
import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionFilesRecord extends TableRecordImpl<SessionFilesRecord> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = 1142629677;

    /**
     * Setter for <code>public.session_files.session</code>.
     */
    public void setSession(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.session_files.session</code>.
     */
    public String getSession() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.session_files.pjnz</code>.
     */
    public void setPjnz(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.session_files.pjnz</code>.
     */
    public String getPjnz() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.session_files.programme</code>.
     */
    public void setProgramme(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.session_files.programme</code>.
     */
    public String getProgramme() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.session_files.survey</code>.
     */
    public void setSurvey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.session_files.survey</code>.
     */
    public String getSurvey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.session_files.anc</code>.
     */
    public void setAnc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.session_files.anc</code>.
     */
    public String getAnc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.session_files.shape</code>.
     */
    public void setShape(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.session_files.shape</code>.
     */
    public String getShape() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SessionFiles.SESSION_FILES.SESSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SessionFiles.SESSION_FILES.PJNZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SessionFiles.SESSION_FILES.PROGRAMME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SessionFiles.SESSION_FILES.SURVEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SessionFiles.SESSION_FILES.ANC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SessionFiles.SESSION_FILES.SHAPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getSession();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPjnz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProgramme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSurvey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAnc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getShape();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSession();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPjnz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProgramme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSurvey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAnc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getShape();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFilesRecord value1(String value) {
        setSession(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFilesRecord value2(String value) {
        setPjnz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFilesRecord value3(String value) {
        setProgramme(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFilesRecord value4(String value) {
        setSurvey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFilesRecord value5(String value) {
        setAnc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFilesRecord value6(String value) {
        setShape(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionFilesRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionFilesRecord
     */
    public SessionFilesRecord() {
        super(SessionFiles.SESSION_FILES);
    }

    /**
     * Create a detached, initialised SessionFilesRecord
     */
    public SessionFilesRecord(String session, String pjnz, String programme, String survey, String anc, String shape) {
        super(SessionFiles.SESSION_FILES);

        set(0, session);
        set(1, pjnz);
        set(2, programme);
        set(3, survey);
        set(4, anc);
        set(5, shape);
    }
}
