/*
 * This file is generated by jOOQ.
*/
package org.imperial.mrc.hint.db.tables.records;


import javax.annotation.Generated;

import org.imperial.mrc.hint.db.tables.SnapshotFile;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SnapshotFileRecord extends UpdatableRecordImpl<SnapshotFileRecord> implements Record5<String, String, String, String, Boolean> {

    private static final long serialVersionUID = -1419613438;

    /**
     * Setter for <code>public.snapshot_file.snapshot</code>.
     */
    public void setSnapshot(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.snapshot_file.snapshot</code>.
     */
    public String getSnapshot() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.snapshot_file.hash</code>.
     */
    public void setHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.snapshot_file.hash</code>.
     */
    public String getHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.snapshot_file.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.snapshot_file.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.snapshot_file.filename</code>.
     */
    public void setFilename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.snapshot_file.filename</code>.
     */
    public String getFilename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.snapshot_file.from_adr</code>.
     */
    public void setFromAdr(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.snapshot_file.from_adr</code>.
     */
    public Boolean getFromAdr() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SnapshotFile.SNAPSHOT_FILE.SNAPSHOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SnapshotFile.SNAPSHOT_FILE.HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SnapshotFile.SNAPSHOT_FILE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SnapshotFile.SNAPSHOT_FILE.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return SnapshotFile.SNAPSHOT_FILE.FROM_ADR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getSnapshot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getFromAdr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSnapshot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getFromAdr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SnapshotFileRecord value1(String value) {
        setSnapshot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SnapshotFileRecord value2(String value) {
        setHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SnapshotFileRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SnapshotFileRecord value4(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SnapshotFileRecord value5(Boolean value) {
        setFromAdr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SnapshotFileRecord values(String value1, String value2, String value3, String value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SnapshotFileRecord
     */
    public SnapshotFileRecord() {
        super(SnapshotFile.SNAPSHOT_FILE);
    }

    /**
     * Create a detached, initialised SnapshotFileRecord
     */
    public SnapshotFileRecord(String snapshot, String hash, String type, String filename, Boolean fromAdr) {
        super(SnapshotFile.SNAPSHOT_FILE);

        set(0, snapshot);
        set(1, hash);
        set(2, type);
        set(3, filename);
        set(4, fromAdr);
    }
}
