#!/usr/bin/env bash
set -ex

HERE=$(dirname $0)
. $HERE/common
(cd ..;
    ./gradlew :userCLI:distDocker -i -Pdocker_version=$GIT_SHA -Pdocker_name=$TAG_IMAGE;
    ./gradlew :userCLI:distDocker -i -Pdocker_version=$GIT_BRANCH -Pdocker_name=$TAG_IMAGE;)
